services:
  shortlify-api:
    build:
      context: ./shortlify-api
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: shortlify
    ports:
      - "3009:3009"
    tty: true
    restart: always
    networks:
      - shortlify-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  shortlify-network:
    driver: bridge

    